spring:
  application:
    name: spring-security-asymetric-encryption
  datasource:
    url: jdbc:postgresql://localhost:5432/postgreses
    hikari:
      username: postgres
      password: pass
      driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false

app:
  security:
    jwt:
      access-token-expiration: 8640000
      refresh-token-expiration: 684800000
    disposable-email: 10minutemail,20minutemail,33mail,5ymail,anonbox,querrillmail

server:
  port: 8081
