spring:
  application:
    name: spring-security-asymetric-encryption
  #config:
    #import: optional:file:.env[properties]
  datasource:
    url: jdbc:postgresql://localhost:5432/postgreses
    hikari:
      password: pass
      username: postgres
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false

app:
  security:
    jwt:
      access-token-expiration: 8640000 # 24 hours for local, but recommend 15 mins for prod.
      refresh-token-expiration: 684800000
    disposable-email: 10minutemail, 20minutemail,33mail,5ymail,anonbox, querrillmail etc
