spring:
  application:
    name: spring-security-asymetric-encryption
  datasource:
    url: jdbc:postgresql://${DB_URL}:${DB_PORT}/${DB_NAME}
    hikari:
      password: ${DB_PASSWORD}
      username: ${DB_USERNAME}
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: false

  app:
    security:
